-- Drop existing roles to avoid ORA-01921
BEGIN
  EXECUTE IMMEDIATE 'DROP ROLE administrateur';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1919 THEN NULL; END IF; -- Role does not exist
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP ROLE agent_reservation';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1919 THEN NULL; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP ROLE personnel_navigant';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1919 THEN NULL; END IF;
END;
/

-- Drop existing users to avoid ORA-01920
BEGIN
  EXECUTE IMMEDIATE 'DROP USER "admin" CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1918 THEN NULL; END IF; -- User does not exist
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP USER "agent1" CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1918 THEN NULL; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP USER "pilote1" CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1918 THEN NULL; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP USER "agent2" CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1918 THEN NULL; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP USER "navigant1" CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1918 THEN NULL; END IF;
END;
/
/

-- Create roles
CREATE ROLE administrateur;
CREATE ROLE agent_reservation;
CREATE ROLE personnel_navigant;

-- Create users
CREATE USER "admin" IDENTIFIED BY "admin123" DEFAULT TABLESPACE USERS;
CREATE USER "agent1" IDENTIFIED BY "agent123" DEFAULT TABLESPACE USERS;
CREATE USER "pilote1" IDENTIFIED BY "pilote123" DEFAULT TABLESPACE USERS;
CREATE USER "agent2" IDENTIFIED BY "agent456" DEFAULT TABLESPACE USERS;
CREATE USER "navigant1" IDENTIFIED BY "navi123" DEFAULT TABLESPACE USERS;

-- Grant roles to users
GRANT administrateur TO "admin";
GRANT agent_reservation TO "agent1";
GRANT personnel_navigant TO "pilote1";
GRANT agent_reservation TO "agent2";
GRANT personnel_navigant TO "navigant1";