-- 1. Rechercher tous les vols de Paris (CDG = ID 1) à New York (JFK = ID 3) le 10 mai 2025
SELECT * FROM VOL
WHERE AEROPORT_DEPART = (
        SELECT ID_AEROPORT FROM AEROPORT WHERE NOM = 'Charles de Gaulle'
      )
  AND AEROPORT_ARRIVEE = (
        SELECT ID_AEROPORT FROM AEROPORT WHERE NOM = 'Heathrow'
      )
  AND TRUNC(DATE_DEPART) = TO_DATE('2025-05-10', 'YYYY-MM-DD');

-- 2. Identifier les passagers ayant réservé un vol mais n’ayant pas embarqué
SELECT P.ID_PASSAGER, P.NOM, P.PRENOM, R.ID_VOL
FROM PASSAGER P
JOIN RESERVATION R ON P.ID_PASSAGER = R.ID_PASSAGER
LEFT JOIN PRESENCE_VOL PV ON R.ID_PASSAGER = PV.ID_PASSAGER AND R.ID_VOL = PV.ID_VOL
WHERE PV.ETAT_PRESENCE IS NULL;

-- 3. Calculer le poids total des bagages par réservation
SELECT ID_RESERVATION, SUM(POIDS) AS POIDS_TOTAL
FROM BAGAGE
GROUP BY ID_RESERVATION;

-- 4. Afficher les membres d’équipage du vol ID 1 avec leurs rôles
SELECT E.ID_EMPLOYE, E.NOM, E.PRENOM, AE.ROLE
FROM EMPLOYE E
JOIN ASSIGNATION_EQUIPAGE AE ON E.ID_EMPLOYE = AE.ID_EMPLOYE
WHERE AE.ID_VOL = 1;

-- 5. Identifier l’avion le plus utilisé
SELECT ID_AVION, COUNT(*) AS NB_UTILISATIONS
FROM VOL
GROUP BY ID_AVION
ORDER BY NB_UTILISATIONS DESC
FETCH FIRST 1 ROWS ONLY;

-- 6. Lister les réservations annulées
SELECT *
FROM RESERVATION
WHERE STATUT = 'Annulée';

-- 7. Calculer le taux d’occupation des vols
SELECT V.ID_VOL,
       ROUND(COUNT(DISTINCT PV.ID_PASSAGER) / A.CAPACITE * 100, 2) AS TAUX_OCCUPATION
FROM VOL V
JOIN AVION A ON V.ID_AVION = A.ID_AVION
LEFT JOIN PRESENCE_VOL PV ON V.ID_VOL = PV.ID_VOL AND PV.ETAT_PRESENCE = 'Présent'
GROUP BY V.ID_VOL, A.CAPACITE;

-- 8. Déterminer le nombre moyen de bagages par passager (including those with zero bags)
SELECT ROUND(AVG(COALESCE(NB_BAGAGES, 0)), 2) AS MOYENNE_BAGAGES
FROM (
  SELECT P.ID_PASSAGER, COUNT(B.ID_BAGAGE) AS NB_BAGAGES
  FROM PASSAGER P
  LEFT JOIN RESERVATION R ON P.ID_PASSAGER = R.ID_PASSAGER
  LEFT JOIN BAGAGE B ON R.ID_RESERVATION = B.ID_RESERVATION
  GROUP BY P.ID_PASSAGER
);